export { SecaoProcesso } from "./SecaoProcesso";
export { SecaoPessoais } from "./SecaoPessoais";
export { SecaoCurso } from "./SecaoCurso";
export { SecaoEmissora } from "./SecaoEmissora";
export { SecaoAcademicos } from "./SecaoAcademicos";
export { SecaoDisciplinas } from "./SecaoDisciplinas";
export { SecaoAtividades } from "./SecaoAtividades";
export { SecaoEstagio } from "./SecaoEstagio";
export { SecaoAssinantes } from "./SecaoAssinantes";
export { SecaoDecisaoJudicial } from "./SecaoDecisaoJudicial";
export { SecaoHabilitacoes } from "./SecaoHabilitacoes";
export { default as HistoricoPreviewDialog } from "./HistoricoPreviewDialog";
