import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Plus, FileSpreadsheet, Download, CheckSquare, Wand2 } from "lucide-react";
import { useDIMOBEntries, useCreateDIMOBEntry, useMarkDIMOBExported, useAutoGenerateDIMOB, dimobEntryTypeLabels } from "@/hooks/useDIMOB";
import { useContracts } from "@/hooks/useContracts";
import { usePeople } from "@/hooks/usePeople";

export default function FinanceDIMOB() {
  const currentYear = new Date().getFullYear();
  const [year, setYear] = useState(currentYear - 1);
  const { data: entries = [], isLoading } = useDIMOBEntries(year);
  const { data: contracts = [] } = useContracts({});
  const { data: people = [] } = usePeople();
  const createEntry = useCreateDIMOBEntry();
  const markExported = useMarkDIMOBExported();
  const autoGenerate = useAutoGenerateDIMOB();
  const [dialogOpen, setDialogOpen] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const [form, setForm] = useState({
    entry_type: "locacao_administracao" as string,
    contract_id: "",
    property_id: "",
    buyer_seller_person_id: "",
    tenant_person_id: "",
    owner_person_id: "",
    transaction_value: 0,
    commission_value: 0,
    notes: "",
  });

  const fmt = (v: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(v);

  const totalTransactions = entries.reduce((s: number, e: any) => s + Number(e.transaction_value), 0);
  const totalCommissions = entries.reduce((s: number, e: any) => s + Number(e.commission_value), 0);
  const unexported = entries.filter((e: any) => !e.exported).length;

  function openNew() {
    setForm({ entry_type: "locacao_administracao", contract_id: "", property_id: "", buyer_seller_person_id: "", tenant_person_id: "", owner_person_id: "", transaction_value: 0, commission_value: 0, notes: "" });
    setDialogOpen(true);
  }

  function handleSave() {
    createEntry.mutate({
      reference_year: year,
      entry_type: form.entry_type,
      contract_id: form.contract_id || undefined,
      property_id: form.property_id || undefined,
      buyer_seller_person_id: form.buyer_seller_person_id || undefined,
      tenant_person_id: form.tenant_person_id || undefined,
      owner_person_id: form.owner_person_id || undefined,
      transaction_value: form.transaction_value,
      commission_value: form.commission_value,
      notes: form.notes || undefined,
    }, { onSuccess: () => setDialogOpen(false) });
  }

  function handleExportSelected() {
    if (selected.length === 0) return;
    markExported.mutate(selected, { onSuccess: () => setSelected([]) });
  }

  function toggleSelect(id: string) {
    setSelected((prev) => prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id]);
  }

  function selectAll() {
    const unexportedIds = entries.filter((e: any) => !e.exported).map((e: any) => e.id);
    setSelected((prev) => prev.length === unexportedIds.length ? [] : unexportedIds);
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold font-display">DIMOB</h1>
          <p className="text-muted-foreground text-sm">Declaração de Informações sobre Atividades Imobiliárias — Receita Federal</p>
        </div>
        <div className="flex gap-2">
          {selected.length > 0 && (
            <Button variant="outline" onClick={handleExportSelected}>
              <CheckSquare className="h-4 w-4 mr-1" /> Marcar {selected.length} como Exportado
            </Button>
          )}
          <Button variant="outline" onClick={() => autoGenerate.mutate(year)} disabled={autoGenerate.isPending}>
            <Wand2 className="h-4 w-4 mr-1" /> Gerar a partir dos Contratos
          </Button>
          <Button onClick={openNew}><Plus className="h-4 w-4 mr-1" /> Nova Entrada</Button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-6">
            <div className="space-y-1.5">
              <Label>Ano-Base</Label>
              <Select value={String(year)} onValueChange={(v) => setYear(Number(v))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {[currentYear - 1, currentYear - 2, currentYear - 3, currentYear].map((y) => (
                    <SelectItem key={y} value={String(y)}>{y}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                <FileSpreadsheet className="h-5 w-5 text-primary" />
              </div>
              <div>
                <p className="text-2xl font-bold">{entries.length}</p>
                <p className="text-xs text-muted-foreground">Entradas ({year})</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <p className="text-sm text-muted-foreground">Total Transacionado</p>
            <p className="text-xl font-bold">{fmt(totalTransactions)}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <p className="text-sm text-muted-foreground">Comissões Declaradas</p>
            <p className="text-xl font-bold">{fmt(totalCommissions)}</p>
            {unexported > 0 && <p className="text-xs text-amber-600 mt-1">{unexported} não exportados</p>}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardContent className="pt-6">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-10">
                  <Checkbox checked={selected.length > 0 && selected.length === entries.filter((e: any) => !e.exported).length} onCheckedChange={selectAll} />
                </TableHead>
                <TableHead>Tipo</TableHead>
                <TableHead>Imóvel</TableHead>
                <TableHead>Comprador/Locatário</TableHead>
                <TableHead>Vendedor/Proprietário</TableHead>
                <TableHead>Valor Transação</TableHead>
                <TableHead>Comissão</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? (
                <TableRow><TableCell colSpan={8} className="text-center py-12 text-muted-foreground">Carregando...</TableCell></TableRow>
              ) : entries.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={8} className="text-center py-12 text-muted-foreground">
                    <FileSpreadsheet className="h-10 w-10 mx-auto mb-2 opacity-30" />
                    Nenhuma entrada DIMOB para {year}.
                  </TableCell>
                </TableRow>
              ) : (
              entries.map((e: any) => {
                  const rentDetails = e.monthly_rent_values && typeof e.monthly_rent_values === "object" ? e.monthly_rent_values : null;
                  return (
                  <TableRow key={e.id}>
                    <TableCell>
                      {!e.exported && <Checkbox checked={selected.includes(e.id)} onCheckedChange={() => toggleSelect(e.id)} />}
                    </TableCell>
                    <TableCell><Badge variant="outline">{dimobEntryTypeLabels[e.entry_type] || e.entry_type}</Badge></TableCell>
                    <TableCell className="font-medium">{e.contracts?.properties?.title || e.property?.title || "—"}</TableCell>
                    <TableCell>{e.tenant?.name || e.buyer_seller?.name || "—"}</TableCell>
                    <TableCell>{e.owner?.name || e.buyer_seller?.name || "—"}</TableCell>
                    <TableCell>{fmt(Number(e.transaction_value))}</TableCell>
                    <TableCell>{fmt(Number(e.commission_value))}</TableCell>
                    <TableCell>
                      <div className="space-y-1">
                        <Badge variant={e.exported ? "default" : "secondary"}>
                          {e.exported ? "Exportado" : "Pendente"}
                        </Badge>
                        {rentDetails && (
                          <div className="text-xs text-muted-foreground space-y-0.5">
                            {rentDetails.ir_withheld > 0 && (
                              <p>IR retido: {fmt(rentDetails.ir_withheld)}</p>
                            )}
                            {rentDetails.net_transferred > 0 && (
                              <p>Líq. repassado: {fmt(rentDetails.net_transferred)}</p>
                            )}
                            {rentDetails.admin_fee > 0 && (
                              <p>Taxa adm: {fmt(rentDetails.admin_fee)}</p>
                            )}
                          </div>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                )})

              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>Nova Entrada DIMOB — Ano {year}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-1.5">
              <Label>Tipo de Operação *</Label>
              <Select value={form.entry_type} onValueChange={(v) => setForm({ ...form, entry_type: v })}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {Object.entries(dimobEntryTypeLabels).map(([k, v]) => (
                    <SelectItem key={k} value={k}>{v}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1.5">
              <Label>Contrato Vinculado</Label>
              <Select value={form.contract_id} onValueChange={(v) => setForm({ ...form, contract_id: v })}>
                <SelectTrigger><SelectValue placeholder="(Opcional)" /></SelectTrigger>
                <SelectContent>
                  {contracts.map((c: any) => (
                    <SelectItem key={c.id} value={c.id}>{c.properties?.title || "Sem imóvel"} — {c.contract_type}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {form.entry_type === "venda" && (
              <div className="space-y-1.5">
                <Label>Comprador / Vendedor</Label>
                <Select value={form.buyer_seller_person_id} onValueChange={(v) => setForm({ ...form, buyer_seller_person_id: v })}>
                  <SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger>
                  <SelectContent>
                    {(people as any[]).map((p) => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
            )}

            {form.entry_type !== "venda" && (
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <Label>Locatário</Label>
                  <Select value={form.tenant_person_id} onValueChange={(v) => setForm({ ...form, tenant_person_id: v })}>
                    <SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger>
                    <SelectContent>
                      {(people as any[]).map((p) => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1.5">
                  <Label>Proprietário</Label>
                  <Select value={form.owner_person_id} onValueChange={(v) => setForm({ ...form, owner_person_id: v })}>
                    <SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger>
                    <SelectContent>
                      {(people as any[]).map((p) => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
              </div>
            )}

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <Label>Valor da Transação *</Label>
                <Input type="number" step="0.01" value={form.transaction_value} onChange={(e) => setForm({ ...form, transaction_value: Number(e.target.value) })} />
              </div>
              <div className="space-y-1.5">
                <Label>Valor da Comissão *</Label>
                <Input type="number" step="0.01" value={form.commission_value} onChange={(e) => setForm({ ...form, commission_value: Number(e.target.value) })} />
              </div>
            </div>

            <div className="space-y-1.5">
              <Label>Observações</Label>
              <Textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} rows={2} />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>Cancelar</Button>
            <Button onClick={handleSave} disabled={!form.entry_type || createEntry.isPending}>Criar Entrada</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
