import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { getAuthTenantId } from "@/lib/tenantUtils";

export const dimobEntryTypeLabels: Record<string, string> = {
  venda: "Compra e Venda",
  locacao_intermediacao: "Locação (Intermediação)",
  locacao_administracao: "Locação (Administração)",
};

export function useDIMOBEntries(year?: number) {
  return useQuery({
    queryKey: ["dimob-entries", year],
    queryFn: async () => {
      let q = supabase
        .from("dimob_entries")
        .select("*, contracts:contract_id ( id, contract_type, monthly_value, total_value, properties:property_id ( id, title ) ), property:property_id ( id, title ), buyer_seller:buyer_seller_person_id ( id, name, cpf_cnpj ), tenant:tenant_person_id ( id, name, cpf_cnpj ), owner:owner_person_id ( id, name, cpf_cnpj )")
        .order("created_at", { ascending: false });
      if (year) q = q.eq("reference_year", year);
      const { data, error } = await q;
      if (error) throw error;
      return data as any[];
    },
  });
}

export function useCreateDIMOBEntry() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (form: {
      reference_year: number;
      entry_type: string;
      contract_id?: string;
      property_id?: string;
      buyer_seller_person_id?: string;
      tenant_person_id?: string;
      owner_person_id?: string;
      transaction_value: number;
      commission_value: number;
      monthly_rent_values?: number[];
      notes?: string;
    }) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Não autenticado");
      const tenant_id = await getAuthTenantId();
      const { error } = await supabase.from("dimob_entries").insert({
        ...form,
        entry_type: form.entry_type as any,
        contract_id: form.contract_id || null,
        property_id: form.property_id || null,
        buyer_seller_person_id: form.buyer_seller_person_id || null,
        tenant_person_id: form.tenant_person_id || null,
        owner_person_id: form.owner_person_id || null,
        monthly_rent_values: form.monthly_rent_values ? JSON.stringify(form.monthly_rent_values) : null,
        generated_at: new Date().toISOString(),
        created_by: user.id,
        tenant_id,
      });
      if (error) throw error;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["dimob-entries"] });
      toast.success("Entrada DIMOB criada!");
    },
    onError: (e: Error) => toast.error(e.message),
  });
}

export function useMarkDIMOBExported() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (ids: string[]) => {
      const { error } = await supabase.from("dimob_entries").update({ exported: true }).in("id", ids);
      if (error) throw error;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["dimob-entries"] });
      toast.success("Entradas marcadas como exportadas!");
    },
    onError: (e: Error) => toast.error(e.message),
  });
}

export function useAutoGenerateDIMOB() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (year: number) => {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Não autenticado");
      const tenant_id = await getAuthTenantId();

      const yearStart = `${year}-01-01`;
      const yearEnd = `${year}-12-31`;
      const { data: contracts, error: cErr } = await supabase
        .from("contracts")
        .select(`*, properties:property_id ( id, title ), contract_parties ( person_id, role, people:person_id ( id, name, cpf_cnpj, person_type ) )`)
        .in("status", ["ativo", "encerrado"])
        .or(`start_date.lte.${yearEnd},end_date.gte.${yearStart},end_date.is.null`);

      if (cErr) throw cErr;
      if (!contracts || contracts.length === 0) throw new Error("Nenhum contrato encontrado para o período.");

      const { data: existing } = await supabase.from("dimob_entries").select("contract_id").eq("reference_year", year);
      const existingContractIds = new Set((existing || []).map((e) => e.contract_id));

      const newEntries: any[] = [];
      for (const c of contracts) {
        if (existingContractIds.has(c.id)) continue;
        const parties = c.contract_parties || [];
        const owner = parties.find((p: any) => p.role === "proprietario");
        const tenantParty = parties.find((p: any) => p.role === "locatario");
        const buyer = parties.find((p: any) => p.role === "comprador");

        if (c.contract_type === "locacao") {
          const { data: paidInstallments } = await supabase.from("contract_installments").select("amount, paid_amount").eq("contract_id", c.id).eq("status", "pago").gte("due_date", yearStart).lte("due_date", yearEnd);
          const totalPaid = (paidInstallments || []).reduce((s: number, i: any) => s + Number(i.paid_amount || i.amount), 0);
          const adminPct = c.admin_fee_percentage || c.commission_percentage || 10;
          const commissionVal = Math.round(totalPaid * adminPct / 100 * 100) / 100;
          const { data: irData } = await supabase.from("ir_withholdings").select("ir_value, reference_month").eq("contract_id", c.id).gte("reference_month", `${year}-01`).lte("reference_month", `${year}-12`);
          const totalIR = (irData || []).reduce((s: number, ir: any) => s + Number(ir.ir_value), 0);
          const { data: transferData } = await supabase.from("owner_transfers").select("net_amount, admin_fee_value").eq("contract_id", c.id).gte("reference_month", `${year}-01`).lte("reference_month", `${year}-12`);
          const totalTransferred = (transferData || []).reduce((s: number, t: any) => s + Number(t.net_amount), 0);

          newEntries.push({
            reference_year: year, entry_type: "locacao_administracao", contract_id: c.id, property_id: c.property_id,
            tenant_person_id: tenantParty?.person_id || null, owner_person_id: owner?.person_id || null,
            transaction_value: totalPaid, commission_value: commissionVal,
            monthly_rent_values: JSON.stringify({ total_paid: totalPaid, admin_fee: commissionVal, ir_withheld: totalIR, net_transferred: totalTransferred }),
            notes: `IR retido: R$ ${totalIR.toFixed(2)}. Líquido repassado: R$ ${totalTransferred.toFixed(2)}.`,
            generated_at: new Date().toISOString(), created_by: user.id, tenant_id,
          });
        } else if (c.contract_type === "venda") {
          newEntries.push({
            reference_year: year, entry_type: "venda", contract_id: c.id, property_id: c.property_id,
            buyer_seller_person_id: buyer?.person_id || owner?.person_id || null,
            transaction_value: Number(c.total_value || 0), commission_value: Number(c.commission_value || 0),
            generated_at: new Date().toISOString(), created_by: user.id, tenant_id,
          });
        }
      }

      if (newEntries.length === 0) throw new Error("Nenhuma nova entrada para gerar (todas já existem).");
      const { error } = await supabase.from("dimob_entries").insert(newEntries as any);
      if (error) throw error;
      return newEntries.length;
    },
    onSuccess: (count) => {
      qc.invalidateQueries({ queryKey: ["dimob-entries"] });
      toast.success(`${count} entradas DIMOB geradas automaticamente!`);
    },
    onError: (e: Error) => toast.error(e.message),
  });
}
